version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    command: gunicorn coffehouseapi_project.wsgi:application --bind 0.0.0.0:8002 --workers 4
    volumes:
      - .:/code
    ports:
      - "8002:8002"
